### ISSUE TITLE
Not requiring .node files for NAN.

### ISSUE THREAD

**Issue by meyer9** [benjamn/install#7]
https://github.com/nodejs/nan

Seems to be a problem with this:

https://github.com/benjamn/install/blob/master/install.js#L6

**Comment by benjamn** [comment]
This library is just a bundling format for ordinary JS modules that can be represented as strings. If you want to be able to import binary `.node` files, you need to define [an `options.fallback` function](https://github.com/benjamn/install/blob/9146a6d6af957e2191dcbbefcd4fb03df6a421f1/install.js#L26-L30).

The function should take [three arguments](https://github.com/benjamn/install/blob/9146a6d6af957e2191dcbbefcd4fb03df6a421f1/install.js#L217-L220):
1. the required module identifier
2. the parent module identifier
3. an error object that should be thrown if no fallback can be found

If successful, the `options.fallback` function should return whatever `require(id)` would return in native Node.
